### ISSUE TITLE
Require not defined

### ISSUE THREAD

**Issue by undavide** [ackzell/heartbeat#1]
Hi,
after installing the dependencies, `npm run dev` builds the project but the web app appears to be broken: upon inspection in the console, I find an `Uncaught ReferenceError: require is not defined` error. 

I'm not that much Webpack skilled, but googling around I've tried to substitute `"env"` to `"es2015"` in `.babelrc`, to no avail. Any suggestion? Thanks!

As a side note, I was trying to build the project to inspect the way you create `_id`s for new remotes – which I've not been able to understand. 

Thanks for sharing this, it has been super-useful!

Davide

**Comment by ackzell** [comment]
Hello @undavide, I'm glad you found it helpful!

I'm very sorry for the late response.

`dev` is a task that will only fire up the Vue.js app. Since you are probably trying to run the whole thing, the app now has "Node" code, meaning it is using those `require` statements as part of the app.

Try running `nwdev` instead, and see if this time you get the desktop app running properly.
On a "normal" webapp running Vue you would not be able to do this, but NW.js allows us to combine both environments: browser and Node.js backend.

Re: `_id`s
You'll notice that I use NeDB for persisting the remotes, so when I am storing them for the first time, they will get a unique id: https://github.com/ackzell/heartbeat/blob/master/src/store/store.js#L83

Hope this helps and it isn't terribly late!

PS. https://github.com/itexico/heartbeat is the repo that has the actual code I write during the YouTube series. It is slightly different since I was trying to improve it for the videos.

Cheers!
